language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION="2.1.0"
  - SYMFONY_VERSION="~2.1"

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit
