dist: trusty

sudo: false

language: php

cache:
    directories:
        - $HOME/.composer/cache/files
        
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly
    - hhvm
        
env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=3.1.*
    - SYMFONY_VERSION=3.2.*
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.0.*
    - SYMFONY_VERSION=4.1.*

matrix:
    fast_failure: true
    include:
        - php: 5.3
          dist: precise
          env: DEPENDENCIES=low
    exclude:
        - php: 5.3
          env: SYMFONY_VERSION=4.0.*
        - php: 5.3
          env: SYMFONY_VERSION=4.1.*
        - php: 5.4
          env: SYMFONY_VERSION=3.0.*
        - php: 5.4
          env: SYMFONY_VERSION=3.1.*
        - php: 5.4
          env: SYMFONY_VERSION=3.2.*
        - php: 5.4
          env: SYMFONY_VERSION=3.3.*
        - php: 5.4
          env: SYMFONY_VERSION=3.4.*
        - php: 5.4
          env: SYMFONY_VERSION=4.0.*
        - php: 5.4
          env: SYMFONY_VERSION=4.1.*
        - php: 5.5
          env: SYMFONY_VERSION=4.0.*
        - php: 5.5
          env: SYMFONY_VERSION=4.1.*
        - php: 5.6
          env: SYMFONY_VERSION=4.0.*
        - php: 5.6
          env: SYMFONY_VERSION=4.1.*
        - php: 7.0
          env: SYMFONY_VERSION=4.0.*
        - php: 7.0
          env: SYMFONY_VERSION=4.1.*
    allow_failures:
        - php: hhvm
        - php: nightly

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo 'memory_limit=-1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:$SYMFONY_VERSION; fi

install:
    - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction; else composer update --prefer-dist --no-interaction; fi;

script: ./vendor/bin/phpunit --coverage-text
